[project]
name = "subtitles-py"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "mcz", email = "unclemcz@qq.com"},
]
dependencies = [
    "openai-whisper",
    "python-dotenv",
    "funasr",
    "torch",
    "torchaudio",
    "modelscope",
    "huggingface-hub",
    "numpy",
    "faster-whisper",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[[tool.pdm.source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[tool.pdm.dev-dependencies]
dev = []
